name: audio_player_tutorial2
description: Musik Sasak App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  just_audio: ^0.9.36
  just_audio_background: ^0.0.1-beta.11 # Tambahkan ini untuk notifikasi

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/audios/
