name: Build Flutter Audio Player

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: 'Nama Aplikasi (Contoh: Musik Sasak)'
        required: true
        default: 'Musik Sasak'
      package_name:
        description: 'Package Name (Contoh: com.ojgrup.musiksasak)'
        required: true
        default: 'com.ojgrup.musiksasak'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install Dependencies
        run: flutter pub get

      - name: Customize App Metadata
        run: |
          # 1. Ganti Nama Aplikasi (Android)
          sed -i 's/android:label=".*"/android:label="${{ github.event.inputs.app_name }}"/g' android/app/src/main/AndroidManifest.xml
          
          # 2. Ganti Package Name (Android)
          OLD_PKG=$(grep "applicationId" android/app/build.gradle | awk '{print $2}' | tr -d '"')
          NEW_PKG="${{ github.event.inputs.package_name }}"
          find android/app -name "build.gradle" -exec sed -i "s/$OLD_PKG/$NEW_PKG/g" {} +
          
          echo "Metadata updated: Name=${{ github.event.inputs.app_name }}, Package=$NEW_PKG"

      - name: Build APK
        run: flutter build apk --release --split-per-abi

      - name: Upload APK Result
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.app_name }}-APK
          path: build/app/outputs/flutter-apk/*.apk
